"""inital

Revision ID: 3fa4ae11e277
Revises: 
Create Date: 2026-03-22 01:18:33.894433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa4ae11e277'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_articles_published_at', 'articles', [sa.text('published_at DESC')], unique=False)
    op.create_index('idx_articles_source', 'articles', ['source'], unique=False)
    op.create_index('idx_articles_source_published', 'articles', ['source', sa.text('published_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_articles_source_published', table_name='articles')
    op.drop_index('idx_articles_source', table_name='articles')
    op.drop_index('idx_articles_published_at', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
